### ISSUE TITLE
Plz Add ESP 8266 Auto Updater !!

### ISSUE THREAD

**Issue by 0x0byalix** [revoxhere/duino-coin#1042]
Plz Add ESP 8266 Auto Updater !!

**Comment by gsrbr** [comment]
Hello @0x0byalix  , this function would be wonderful... But it can be a big problem too... basically because of this problems:

1. Security: It's very difficult to keep auto upadate functions security, if someone can break the security system of the auto-updater can do anything with your IOT
2. Traffic: would be difficult to manage data traffic in times of update
3. Memory: The flash chip size should be large enough to hold the old sketch (currently running) and the new sketch (OTA) at the same time... [_source_](https://arduino-esp8266.readthedocs.io/en/latest/ota_updates/readme.html)
4. OTA centralization Difficulty: We must also not forget the difficulty of centralizing the ota update on a server outside the network where the ESPs are

Due to this and other issues, we haven't developed an auto update solution for the ESPs... But this is an open source project, so if you find a safe/security and full functional solution feel free to share it with us

**Comment by 0x0byalix** [comment]
Ok !!
But when will u resolve the ddos attack issue .
