### ISSUE TITLE
Очередная хуйня с web-кошельком

### ISSUE THREAD

**Issue by gravedigger21** [revoxhere/duino-coin#1061]
Опять не могу войти в кошелек. Ошибка - вы используете прокси. Какой нахрен прокси?

**Comment by gsrbr** [comment]
Hello @gravedigger21 , please always prefer to use English to open issues, and avoid saying bad words.

**What is proxy:** A proxy server is any machine that translates traffic between networks or protocols. It’s an intermediary server separating end-user clients from the destinations that they browse. Proxy servers provide varying levels of functionality, security, and privacy depending on your use case, needs, or company policy. [Source](https://www.varonis.com/blog/what-is-a-proxy-server/)

This error can also occur due to using VPN.

**What is VPN:** VPN stands for "Virtual Private Network" and describes the opportunity to establish a protected network connection when using public networks. VPNs encrypt your internet traffic and disguise your online identity. This makes it more difficult for third parties to track your activities online and steal data. The encryption takes place in real time.

Make sure you are not using proxy, vpn, tor network, or even firewall/antivirus software that has this function enabled by default

**Comment by gravedigger21** [comment]
> 
> 
> Hello @gravedigger21 , please always prefer to use English to open issues, and avoid saying bad words.
> 
> **What is proxy:** A proxy server is any machine that translates traffic between networks or protocols. It’s an intermediary server separating end-user clients from the destinations that they browse. Proxy servers provide varying levels of functionality, security, and privacy depending on your use case, needs, or company policy. [Source](https://www.varonis.com/blog/what-is-a-proxy-server/)
> 
> This error can also occur due to using VPN.
> 
> **What is VPN:** VPN stands for "Virtual Private Network" and describes the opportunity to establish a protected network connection when using public networks. VPNs encrypt your internet traffic and disguise your online identity. This makes it more difficult for third parties to track your activities online and steal data. The encryption takes place in real time.
> 
> Make sure you are not using proxy, vpn, tor network, or even firewall/antivirus software that has this function enabled by default

I myself know what a proxy, vpn, etc. is. And if I had used any of this, I would not have asked this question. As for bad words - given the constant problems with your services, there are simply no other words left

**Comment by revoxhere** [comment]
I suggest not using duino if it only causes frustration for you

**Comment by gravedigger21** [comment]
I myself decide what to do

**Comment by revoxhere** [comment]
Yep, not arguing with that, just suggested something like you did

**Comment by BastelPichi** [comment]
Closing this as its useless.
